name: raindrop_workspace
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - packages/raindrop
  - packages/raindrop_postgres
  - packages/raindrop_postgres/example
  - packages/raindrop_sqlite
  - packages/raindrop_sqlite/example
  - packages/raindrop_cli
  - packages/raindrop_test

dev_dependencies:
  coverage: ^1.15.1
  melos: ^8.2.2
  path: ^1.9.1
  very_good_analysis: ^10.3.0

melos:
  repository: https://github.com/wolfenrain/raindrop

  command:
    version:
      branch: main
      linkToCommits: true
      workspaceChangelog: true
      hooks:
        preCommit: >-
          dart tool/sync_versions.dart &&
          git add packages/*/lib/src/version.dart

  scripts:
    analyze:
      exec: dart analyze

    format:
      exec: dart format --output=none --set-exit-if-changed .
    format:fix:
      exec: dart format .

    test:
      description: Runs each package's unit and integration tests.
      steps:
        - test:unit
        - test:integration
    test:unit:
      description: Runs each package's unit tests.
      packageFilters:
        dirExists: test
      exec:
        concurrency: 1
        command: dart ../../tool/coverage.dart
    test:integration:
      description: Runs each package's integration tests.
      packageFilters:
        dirExists: integration_test
      exec:
        concurrency: 1
        command: dart test integration_test
