name: raindrop_cli
description: The command line tool for raindrop that generates and embeds SQL schema migrations.
version: 0.1.0
repository: https://github.com/wolfenrain/raindrop/tree/main/packages/raindrop_cli
issue_tracker: https://github.com/wolfenrain/raindrop/issues
topics:
  - sql
  - database
  - migrations
  - cli
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^14.1.0
  args: ^2.4.0
  crypto: ^3.0.7
  meta: ^1.15.0
  path: ^1.8.0
  raindrop: ^0.1.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.24.0

executables:
  raindrop: raindrop
