name: raindrop_example
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  raindrop:
    path: ../
  raindrop_sqlite:
    path: ../../raindrop_sqlite
  sqlite3: ^3.5.1
