name: raindrop_postgres
description: The Postgres driver for raindrop, built on top of the postgres package.
version: 0.1.0
repository: https://github.com/wolfenrain/raindrop/tree/main/packages/raindrop_postgres
issue_tracker: https://github.com/wolfenrain/raindrop/issues
topics:
  - sql
  - database
  - postgres
  - migrations
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  postgres: ">=3.0.0 <4.0.0"
  raindrop: ^0.1.0

dev_dependencies:
  mocktail: ^1.0.3
  raindrop_test: ^0.1.0
  test: ^1.25.2
