import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

import 'package:path/path.dart' as p;

import 'package:raindrop_cli/src/core/snapshot.dart';
import 'package:raindrop_cli/src/introspect/schema_locator.dart';

/// Builds the current schema snapshot by **running** the project's schema.
class SnapshotRunner {
  SnapshotRunner._();

  static const _generatedPath = '.dart_tool/raindrop/schema_snapshot_main.dart';

  /// Describes the schema under [schemaPath] as it actually behaves.
  ///
  /// [dialect] selects which tables count, matching how one schema directory
  /// can hold tables for more than one database.
  static Future<SchemaSnapshot> build({
    required String schemaPath,
    required String dialect,
    required String configDir,
    String? prevId,
  }) async {
    final schemas = await SchemaLocator().locate(schemaPath);
    if (schemas.isEmpty) {
      return SchemaSnapshot(
        version: SchemaSnapshot.currentVersion,
        dialect: dialect,
        id: SchemaSnapshot.generateId(),
        prevId: prevId ?? SchemaSnapshot.nullUuid,
        tables: const {},
      );
    }

    final packageConfig = _findPackageConfig(configDir);
    if (packageConfig == null) {
      throw StateError(
        'package_config.json not found. Run "dart pub get" first.',
      );
    }
    final packages = _readPackages(packageConfig);

    final entrypoint = File(p.join(configDir, _generatedPath));
    entrypoint.parent.createSync(recursive: true);
    entrypoint.writeAsStringSync(
      _entrypointSource(schemas, dialect, packages),
    );

    final response = await _runInIsolate(
      entrypoint.uri,
      packageConfig: packageConfig.uri,
    );

    final document = (response['snapshot']! as Map).cast<String, Object?>();
    return SchemaSnapshot.fromJson(jsonEncode(document)).copyWith(
      id: SchemaSnapshot.generateId(),
      prevId: prevId ?? SchemaSnapshot.nullUuid,
    );
  }

  /// The throwaway entrypoint: import every schema library, hand every table
  /// to `buildSnapshot`, reply.
  static String _entrypointSource(
    List<LocatedSchema> schemas,
    String dialect,
    Map<String, String> packages,
  ) {
    final imports = <String, String>{};
    final references = <String>[];

    for (final schema in schemas) {
      final uri = _packageUri(schema.filePath, packages);
      final alias = imports.putIfAbsent(uri, () => 's${imports.length}');
      references.add('$alias.${schema.variableName}');
    }

    final dialectPackage = 'raindrop_$dialect';
    if (!packages.containsKey(dialectPackage)) {
      throw StateError(
        'Dialect package "$dialectPackage" not found. Make sure it is listed '
        'in your pubspec.yaml dependencies.',
      );
    }

    final buffer = StringBuffer()
      ..writeln('// GENERATED by raindrop. Regenerated on every run.')
      ..writeln("import 'dart:isolate';")
      ..writeln()
      ..writeln("import 'package:raindrop/introspect.dart';")
      ..writeln("import 'package:$dialectPackage/$dialectPackage.dart';");
    for (final entry in imports.entries) {
      buffer.writeln("import '${entry.key}' as ${entry.value};");
    }
    buffer
      ..writeln()
      ..writeln('void main(List<String> args, SendPort sendPort) {')
      ..writeln('  final receive = ReceivePort();')
      ..writeln('  sendPort.send(receive.sendPort);')
      ..writeln('  receive.listen((message) {')
      ..writeln('    final request = (message as Map).cast<String, Object?>();')
      ..writeln("    final reply = request['replyPort']! as SendPort;")
      ..writeln('    try {')
      ..writeln('      reply.send({')
      ..writeln("        'success': true,")
      ..writeln("        'snapshot': buildSnapshot(")
      ..writeln('          [${references.join(', ')}],')
      // The driver's own exported const, so this file never has to know a
      // dialect class's name.
      ..writeln('          dialect: dialect,')
      ..writeln("          dialectName: '$dialect',")
      ..writeln('        ),')
      ..writeln('      });')
      ..writeln('    } catch (error, stack) {')
      ..writeln("      reply.send({")
      ..writeln("        'success': false,")
      ..writeln(r"        'error': '$error\n$stack',")
      ..writeln('      });')
      ..writeln('    }')
      ..writeln('  });')
      ..writeln('}');
    return buffer.toString();
  }

  /// Rewrites an absolute path under a package's `lib/` as a `package:` URI.
  static String _packageUri(String filePath, Map<String, String> packages) {
    for (final entry in packages.entries) {
      final lib = p.join(entry.value, 'lib');
      if (!p.isWithin(lib, filePath)) continue;
      return 'package:${entry.key}/${p.relative(filePath, from: lib)}';
    }
    throw StateError(
      'Schema file "$filePath" is not inside a package\'s lib/ directory, so '
      'it cannot be imported. Move the schema under lib/',
    );
  }

  /// Package name to absolute root, from package_config.json.
  static Map<String, String> _readPackages(File configFile) {
    final config =
        jsonDecode(configFile.readAsStringSync()) as Map<String, dynamic>;
    final configDir = p.dirname(configFile.path);
    return {
      for (final package
          in (config['packages'] as List).cast<Map<String, dynamic>>())
        package['name'] as String: _resolveRoot(
          package['rootUri'] as String,
          configDir,
        ),
    };
  }

  static String _resolveRoot(String rootUri, String configDir) {
    if (rootUri.startsWith('file://')) return p.fromUri(Uri.parse(rootUri));
    return p.normalize(p.join(configDir, rootUri));
  }

  /// Walks up for `.dart_tool/package_config.json`, so a package inside a
  /// workspace finds the root's config.
  static File? _findPackageConfig(String startPath) {
    var current = Directory(startPath).absolute;
    while (true) {
      final configFile = File(
        p.join(current.path, '.dart_tool', 'package_config.json'),
      );
      if (configFile.existsSync()) return configFile;
      final parent = current.parent;
      if (parent.path == current.path) return null;
      current = parent;
    }
  }

  static Future<Map<String, Object?>> _runInIsolate(
    Uri entryPointUri, {
    required Uri packageConfig,
  }) async {
    final receivePort = ReceivePort();
    final errorPort = ReceivePort();
    Isolate? isolate;
    try {
      isolate = await Isolate.spawnUri(
        entryPointUri,
        const [],
        receivePort.sendPort,
        onError: errorPort.sendPort,
        packageConfig: packageConfig,
      );

      // A schema that fails to compile or throws while initialising never
      // sends its port, so race the error channel or this would hang.
      final failure = errorPort.first.then((error) => throw StateError(
            'The schema could not be loaded:\n$error',
          ));
      final isolateSendPort =
          await Future.any([receivePort.first, failure]) as SendPort;

      final responsePort = ReceivePort();
      isolateSendPort.send({'replyPort': responsePort.sendPort});
      final response = await Future.any([responsePort.first, failure])
          as Map<Object?, Object?>;
      responsePort.close();

      if (response['success'] != true) {
        throw StateError('Building the schema snapshot failed:\n'
            '${response['error']}');
      }
      return response.cast<String, Object?>();
    } finally {
      receivePort.close();
      errorPort.close();
      isolate?.kill(priority: Isolate.immediate);
    }
  }
}
