name: raindrop
description: A type-safe SQL toolkit for Dart that requires no code generation.
version: 0.0.1
repository: https://github.com/wolfenrain/raindrop/tree/main/packages/raindrop
issue_tracker: https://github.com/wolfenrain/raindrop/issues
topics:
  - sql
  - database
  - orm
  - migrations
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  crypto: ^3.0.6
  meta: ^1.15.0
  path: ^1.9.1

dev_dependencies:
  raindrop_test: ^0.0.1
  test: ^1.25.2
