name: raindrop_sqlite_example
publish_to: none
resolution: workspace

environment:
  sdk: ">3.5.0-0<=4.0.0"

dependencies:
  raindrop:
    path: ../../raindrop
  raindrop_sqlite:
    path: ../

dev_dependencies:
  raindrop_cli:
    path: ../../raindrop_cli