name: Prepare release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Version as prerelease"
        required: false
        default: false
        type: boolean

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: 🚀 Version packages
        uses: bluefireteam/melos-action@v3
        with:
          run-versioning: ${{ inputs.prerelease == false }}
          run-versioning-prerelease: ${{ inputs.prerelease == true }}
          publish-dry-run: true
          create-pr: true
